#!/bin/bash
java -cp 'jars/*' -Djava.security.manager \
     -Djava.security.policy=dcvm.policy \
     fr.sorbonne_u.components.registry.GlobalRegistry config.xml &

java -ea -Xms2m -cp 'jars/*' -Djava.security.manager \
     -Djava.security.policy=dcvm.policy \
     fr.sorbonne_u.components.cvm.utils.DCVMCyclicBarrier config.xml &

java -ea -cp 'jars/*' -Djava.security.manager \
     -Djava.security.policy=dcvm.policy \
     distributedcvm.DistributedCVM controleur config.xml &

java -ea -cp 'jars/*' -Djava.security.manager \
     -Djava.security.policy=dcvm.policy \
     distributedcvm.DistributedCVM compteur config.xml &

java -ea -cp 'jars/*' -Djava.security.manager \
     -Djava.security.policy=dcvm.policy \
     distributedcvm.DistributedCVM refri config.xml &

java -ea -cp 'jars/*' -Djava.security.manager \
     -Djava.security.policy=dcvm.policy \
     distributedcvm.DistributedCVM seche config.xml &
     
java -ea -cp 'jars/*' -Djava.security.manager \
     -Djava.security.policy=dcvm.policy \
     distributedcvm.DistributedCVM eolienne config.xml &
     
java -ea -cp 'jars/*' -Djava.security.manager \
     -Djava.security.policy=dcvm.policy \
     distributedcvm.DistributedCVM lave config.xml &

java -ea -cp 'jars/*' -Djava.security.manager \
     -Djava.security.policy=dcvm.policy \
     distributedcvm.DistributedCVM groupe config.xml &

