#!/bin/bash
if [ -z "$1" ]; then 
  echo usage: $0 testNumber jvmName
  exit
 fi
java -cp 'jars/*' -Djava.security.manager \
     -Djava.security.policy=dcvm.policy \
     src.tests.Distributed $2 config.xml